  name: Locations
  main: me.ksviety.plugins.mc.locations.Plugin
  version: 1.0
  author: ksviety
  commands:
    adminlocations:
      permission: ksviety.locations.admin
      usage: /adminlocations <sub-command> [param1, param2, ...]
      aliases: alocations
    fasttravel:
      permission: ksviety.locations.fasttravel
      usage: /fasttravel <location-name>
      aliases: ft