  name: Locations
  main: me.ksviety.plugins.mc.locations.Plugin
  version: 1.0
  author: ksviety
  commands:
    locations:
      permission: ksviety.locations.admin
      usage: /locations <sub-command> [param1, param2, ...]
    fasttravel:
      permission: ksviety.locations.fasttravel
      usage: /fasttravel|ft <location-name>
      aliases: ft