  name: Locations
  main: me.ksviety.plugins.mc.locations.Plugin
  version: "1.3.2"
  author: ksviety
  commands:
    adminlocations:
      permission: ksviety.locations.admin
      usage: /adminlocations <sub-command> [param1, param2, ...]
      aliases: alocations
    travel:
      permission: ksviety.locations.travel
      usage: /travel <location-name>
      aliases: [ft, fasttravel]
  permissions:
    ksviety.locations.travel.others:
      default: op
    ksviety.locations.list:
      default: op
      description: Unlocks all locations

